import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/navbar/Navbar'

const urbanist = Urbanist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Primera Fe - Sitio Oficial de Primera Fe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${urbanist.variable} antialiased `}
      >
        <Navbar />
        <main className="">{children}</main>
      </body>
    </html>
  )
}
